### ISSUE TITLE
Keepalived only on master nodes.

### ISSUE THREAD

**Issue by rbo** [stormshift/support#118]
https://docs.openshift.com/container-platform/4.11/installing/installing_bare_metal_ipi/ipi-install-installation-workflow.html#configure-network-components-to-run-on-the-control-plane_ipi-install-installation-workflow
```
$ oc get pods -n openshift-kni-infra -l app=kni-infra-vrrp
NAME                                 READY   STATUS    RESTARTS       AGE
keepalived-inf4.coe.muc.redhat.com   2/2     Running   22 (31h ago)   38d
keepalived-inf44                     2/2     Running   19 (31h ago)   38d
keepalived-inf5.coe.muc.redhat.com   2/2     Running   19 (31h ago)   38d
keepalived-inf6.coe.muc.redhat.com   2/2     Running   19 (31h ago)   38d
keepalived-inf7                      2/2     Running   21 (31h ago)   38d
keepalived-inf8                      2/2     Running   15 (31h ago)   7d6h
```

**Comment by rbo** [comment]
```
$ oc get pods -n openshift-kni-infra -l app=kni-infra-vrrp
NAME                                 READY   STATUS    RESTARTS       AGE
keepalived-inf4.coe.muc.redhat.com   2/2     Running   22 (35h ago)   38d
keepalived-inf5.coe.muc.redhat.com   2/2     Running   19 (35h ago)   38d
keepalived-inf6.coe.muc.redhat.com   2/2     Running   19 (35h ago)   38d
```

Console doens't work anymore:
```
 $ curl -v https://console-openshift-console.apps.cluster.coe.muc.redhat.com/
*   Trying 10.32.111.127:443...
* connect to 10.32.111.127 port 443 failed: Connection refused
* Failed to connect to console-openshift-console.apps.cluster.coe.muc.redhat.com port 443 after 38 ms: Connection refused
* Closing connection 0
curl: (7) Failed to connect to console-openshift-console.apps.cluster.coe.muc.redhat.com port 443 after 38 ms: Connection refused
```

**Comment by rbo** [comment]
IP is at node inf6
```
[root@inf1 ~]# arping -I eno1 10.32.111.127
ARPING 10.32.111.127 from 10.32.96.1 eno1
Unicast reply from 10.32.111.127 [24:6E:96:92:64:48]  0.666ms
Unicast reply from 10.32.111.127 [24:6E:96:92:64:48]  0.707ms
^CSent 2 probes (1 broadcast(s))
Received 2 response(s)
[root@inf1 ~]# arping -I eno1 10.32.96.6
ARPING 10.32.96.6 from 10.32.96.1 eno1
Unicast reply from 10.32.96.6 [24:6E:96:92:64:48]  0.697ms
^CSent 1 probes (1 broadcast(s))
Received 1 response(s)
[root@inf1 ~]# 
```

**Comment by rbo** [comment]
Fixed, ingress controller was not proper configures:

```yaml
apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: default
  namespace: openshift-ingress-operator
  annotations:
    argocd.argoproj.io/sync-options: "ServerSideApply=true,Validate=false"
spec:
  replicas: 3
  endpointPublishingStrategy:
    type: HostNetwork
  nodePlacement:
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/master: ""

```
