### ISSUE TITLE
sso.coe sometimes HTTP ERROR 431

### ISSUE THREAD

**Issue by rbo** [stormshift/support#168]
Sometimes if I'm log in via COE-SSO or COE-SSO-Admin at the ISAR cluster I'm running into an HTTP ERROR 431

**Comment by rbo** [comment]
In general: 431 Request Header Fields Too Large

**Comment by rbo** [comment]
https://github.com/keycloak/keycloak/issues/13933

Work-a-round: quarkus.http.limits.max-header-size=40K

QUARKUS_HTTP_HTTP2=false
QUARKUS_HTTP_LIMITS_MAX_HEADER_SIZE=40k

Fixed via:

```yaml
  unsupported:
    podTemplate:
      spec:
        containers:
          - env:
            - name: QUARKUS_HTTP_HTTP2
              value: false
            - name: QUARKUS_HTTP_LIMITS_MAX_HEADER_SIZE
              value: 40k
```
