### ISSUE TITLE
Erratic Network Performance

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#181]
Some MicroShift Demos need to tranfer large amounts of data (>1.6G) over the network.
During demos, I noticed a wildly different performance of that part - sometimes its lightning fast, sometimes slow as hell.
Hence I did some measurements using ipferf3 running in sender/receiver pods across different nodes.
The throughput measurements range from 19 GBit/sec (from inf8 to inf8, local) to only 0.4 GBit/sec (inf7 -> in44).
CPU utlisation of the nodes might play a factor (keep in mind, >50% CPU utili tips over the phys. core threshold).

See the measurements results here: https://docs.google.com/spreadsheets/d/1Pd0i9BmikUEwIfqRuDbmh3Skklvu__CimsBamZYnraQ/edit#gid=0
 
Tooling Deployment can be seen here: https://console-openshift-console.apps.isar.coe.muc.redhat.com/k8s/ns/dfroehli-perftst/apps~v1~Deployment

**Comment by DanielFroehlich** [comment]
[deploy-isar.zip](https://github.com/user-attachments/files/15758563/deploy-isar.zip)
tooling deployment yaml

**Comment by DanielFroehlich** [comment]
@rbo would you mind to take a look please?

**Comment by rbo** [comment]
|Server|Switch|
|---|---|
|ucs56|arista-rj45|
|ucs57|arista-rj45|
|inf8|arista-rj45|
|inf7|arista-rj45|
|inf44|arista-sfp|

**Comment by rbo** [comment]
Looks like a upgrade is running
![image](https://github.com/stormshift/support/assets/36604/b7e0a371-0248-4084-863c-d4fb23675aed)

**Comment by rbo** [comment]
Try the curl from another pod on the same node:
```
$ oc project rbohne-hcp-sendling
Now using project "rbohne-hcp-sendling" on server "https://api.isar.coe.muc.redhat.com:6443".
$ oc get pods -o wide | grep sendling-10d195e8-j8czd
virt-launcher-sendling-10d195e8-j8czd-sjshq           1/1     Running     0              11d     10.128.10.152   inf44   <none>           1/1
$ oc rsh virt-launcher-sendling-10d195e8-j8czd-sjshq
sh-5.1$ curl -k https://ignition-server-rbohne-hcp-sendling.apps.isar.coe.muc.redhat.com/ignition
curl: (6) Could not resolve host: ignition-server-rbohne-hcp-sendling.apps.isar.coe.muc.redhat.com
sh-5.1$ exit
exit
command terminated with exit code 6
$ oc get pods -o wide | grep inf44
cluster-policy-controller-74964cb9d6-6pqmj            1/1     Running     6 (9d ago)     14d     10.128.10.55    inf44   <none>           <none>
etcd-1                                                3/3     Running     4 (13d ago)    13d     10.128.10.17    inf44   <none>           <none>
ignition-server-5b4567866-b7ksx                       1/1     Running     0              14d     10.128.10.56    inf44   <none>           <none>
ignition-server-proxy-57c4f77c97-6qn9r                1/1     Running     0              14d     10.128.10.57    inf44   <none>           <none>
konnectivity-agent-8599fd5d6b-f8nkz                   1/1     Running     0              14d     10.128.10.58    inf44   <none>           <none>
kube-apiserver-86548cbbbf-bhsfj                       4/4     Running     0              14d     10.128.10.29    inf44   <none>           <none>
kube-controller-manager-5fc9d96bdf-5x4lp              1/1     Running     6 (9d ago)     14d     10.128.10.59    inf44   <none>           <none>
kube-scheduler-5b5c9478f4-98vnz                       1/1     Running     1 (9d ago)     14d     10.128.10.51    inf44   <none>           <none>
network-node-identity-8495fd79d9-sqkbl                3/3     Running     16 (13d ago)   14d     10.128.10.30    inf44   <none>           <none>
oauth-openshift-6b8fc486c9-xb6s8                      2/2     Running     0              10m     10.128.10.252   inf44   <none>           <none>
openshift-apiserver-778f9db75c-6pjb5                  3/3     Running     6 (9d ago)     14d     10.128.10.32    inf44   <none>           <none>
openshift-controller-manager-5578f894bb-6rkvb         1/1     Running     0              14d     10.128.10.61    inf44   <none>           <none>
openshift-oauth-apiserver-584f69b7f9-9qd99            2/2     Running     6 (9d ago)     14d     10.128.10.33    inf44   <none>           <none>
openshift-route-controller-manager-869c7c988b-kp2kh   1/1     Running     10 (9d ago)    14d     10.128.10.60    inf44   <none>           <none>
ovnkube-control-plane-75bffb695c-bxpzh                3/3     Running     17 (13d ago)   14d     10.128.10.34    inf44   <none>           <none>
packageserver-7f976d7855-bp87j                        2/2     Running     0              14d     10.128.10.35    inf44   <none>           <none>
virt-launcher-sendling-10d195e8-j8czd-sjshq           1/1     Running     0              11d     10.128.10.152   inf44   <none>           1/1
$ oc rsh packageserver-7f976d7855-bp87j
Defaulted container "packageserver" out of: packageserver, socks5-proxy, availability-prober (init)
sh-4.4$ curl -k https://ignition-server-rbohne-hcp-sendling.apps.isar.coe.muc.redhat.com/ignition
Unauthorized
sh-4.4$ cat /etc/resolv.conf 
search rbohne-hcp-sendling.svc.cluster.local svc.cluster.local cluster.local isar.coe.muc.redhat.com coe.muc.redhat.com
nameserver 172.30.0.10
options ndots:5
sh-4.4$ 
```
=> works, Unauthorized is expected.

**Comment by rbo** [comment]
Resolve conf is the same.

```
$ oc get pods -o yaml packageserver-7f976d7855-bp87j | grep -i dns
          "dns": {}
  dnsPolicy: ClusterFirst
$ oc get pods -o yaml virt-launcher-sendling-10d195e8-j8czd-sjshq | grep -i dns
          "dns": {}
  dnsPolicy: ClusterFirst
$ 
``

**Comment by rbo** [comment]
![image](https://github.com/stormshift/support/assets/36604/12dec820-dd59-4342-bae4-78c44e0a101f)
I can reproduct...

**Comment by rbo** [comment]
How to run the tests: https://github.com/openshift-examples/ipferf3 

Feel free to reopen if needed

**Comment by DanielFroehlich** [comment]
I did a re-test inf44->inf7
With CPU load <50% of both nodes, I get ~5 g/s
With CPU load >50% (by running pods with "stress", burning CPU cores away, I get ~1.5 g/s

I think this rely  relates to https://github.com/stormshift/support/issues/178 
and hyperthreading
@rbo wdyt?

**Comment by rbo** [comment]
@DanielFroehlich can you provide more information how to you run your tests?

```
$ oc get pods -o wide
NAME                      READY   STATUS              RESTARTS   AGE   IP            NODE    NOMINATED NODE   READINESS GATES
iperf-hostnetwork-4f2zm   0/1     ContainerCreating   0          7s    10.32.96.8    inf8    <none>           <none>
iperf-hostnetwork-8ssf6   0/1     ContainerCreating   0          7s    10.32.96.44   inf44   <none>           <none>
iperf-hostnetwork-ctpjm   1/1     Running             0          7s    10.32.96.7    inf7    <none>           <none>
iperf-hostnetwork-k84jt   0/1     ContainerCreating   0          7s    10.32.96.57   ucs57   <none>           <none>
iperf-hostnetwork-nsxtx   0/1     ContainerCreating   0          7s    10.32.96.56   ucs56   <none>           <none>
$ oc rsh iperf-hostnetwork-8ssf6
sh-5.1$ iperf3 --client 10.32.96.7 --time 60 --parallel 4
Connecting to host 10.32.96.7, port 5201
...
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  13.2 GBytes  1.89 Gbits/sec  11456             sender
[  5]   0.00-60.04  sec  13.2 GBytes  1.88 Gbits/sec                  receiver
[  7]   0.00-60.00  sec  15.8 GBytes  2.26 Gbits/sec  13341             sender
[  7]   0.00-60.04  sec  15.8 GBytes  2.26 Gbits/sec                  receiver
[  9]   0.00-60.00  sec  16.0 GBytes  2.28 Gbits/sec  12367             sender
[  9]   0.00-60.04  sec  16.0 GBytes  2.28 Gbits/sec                  receiver
[ 11]   0.00-60.00  sec  13.2 GBytes  1.88 Gbits/sec  10697             sender
[ 11]   0.00-60.04  sec  13.2 GBytes  1.88 Gbits/sec                  receiver
[SUM]   0.00-60.00  sec  58.1 GBytes  8.32 Gbits/sec  47861             sender
[SUM]   0.00-60.04  sec  58.1 GBytes  8.31 Gbits/sec                  receiver

iperf Done.
sh-5.1$ exit
$ oc adm top node
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%   
inf4    2962m        19%    21437Mi         8%        
inf44   10873m       34%    69532Mi         38%       
inf5    1352m        8%     19752Mi         7%        
inf6    2653m        17%    23314Mi         9%        
inf7    9806m        15%    56408Mi         22%       
inf8    3005m        4%     45632Mi         18%       
ucs56   26146m       21%    227540Mi        22%       
ucs57   6724m        5%     104793Mi        10%  
```

**Comment by rbo** [comment]
Pods are still running in `rbohne-iperf` namesapce.

**Comment by DanielFroehlich** [comment]
[Archive.zip](https://github.com/user-attachments/files/15953627/Archive.zip)
I am running ipferf and stress using the attached manifests.

**Comment by rbo** [comment]
Meanwhile, we disabled hyperthreading (#178) as well and updated the cluster to 4.17 (#205)

**Comment by rbo** [comment]
Just test inf44 <-> inf7

```
iperf3 % oc label node/{inf44,inf7} iperf-deploy=true
# Drain node
iperf3 % oc adm drain -l iperf-deploy=true --ignore-daemonsets --delete-emptydir-data
# deployed iperf via SDN and stress-test
iperf3 % oc adm top node -l iperf-deploy=true
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
inf44   10150m       63%    5042Mi          2%
inf7    16381m       51%    5513Mi          2%
iperf3 % oc get pods -o wide
NAME                            READY   STATUS    RESTARTS   AGE     IP             NODE    NOMINATED NODE   READINESS GATES
iperf-2cd6j                     1/1     Running   0          43m     10.128.8.28    inf44   <none>           <none>
iperf-d8sg2                     1/1     Running   0          43m     10.128.16.71   inf7    <none>           <none>
stress-cpu-server-inf44-4wgkz   1/1     Running   0          38s     10.128.8.32    inf44   <none>           <none>
stress-cpu-server-inf7-dhwhx    1/1     Running   0          3m11s   10.128.16.79   inf7    <none>           <none>
# inf7 stress --cpu 16
# inf44 stress --cpu 10
iperf3 % oc rsh iperf-d8sg2
sh-5.1$ iperf3 --client 10.128.8.28 --time 60 --parallel 4
....
[ ID] Interval           Transfer     Bitrate         Retr
[  5]   0.00-60.00  sec  15.6 GBytes  2.23 Gbits/sec  102             sender
[  5]   0.00-60.04  sec  15.6 GBytes  2.23 Gbits/sec                  receiver
[  7]   0.00-60.00  sec  15.6 GBytes  2.23 Gbits/sec  143             sender
[  7]   0.00-60.04  sec  15.6 GBytes  2.23 Gbits/sec                  receiver
[  9]   0.00-60.00  sec  15.8 GBytes  2.27 Gbits/sec   96             sender
[  9]   0.00-60.04  sec  15.8 GBytes  2.26 Gbits/sec                  receiver
[ 11]   0.00-60.00  sec  15.8 GBytes  2.27 Gbits/sec   96             sender
[ 11]   0.00-60.04  sec  15.8 GBytes  2.26 Gbits/sec                  receiver
[SUM]   0.00-60.00  sec  62.8 GBytes  9.00 Gbits/sec  437             sender
[SUM]   0.00-60.04  sec  62.8 GBytes  8.99 Gbits/sec                  receiver
```

Let's try more CPU stress 

```
# inf7 stress --cpu 22
# inf44 stress --cpu 10

iperf3 % oc adm top node -l iperf-deploy=true
NAME    CPU(cores)   CPU%   MEMORY(bytes)   MEMORY%
inf44   10199m       64%    5085Mi          2%
inf7    22294m       69%    5598Mi          2%
iperf3 % oc get pods -o wide
NAME                            READY   STATUS    RESTARTS   AGE    IP             NODE    NOMINATED NODE   READINESS GATES
iperf-2cd6j                     1/1     Running   0          55m    10.128.8.28    inf44   <none>           <none>
iperf-d8sg2                     1/1     Running   0          56m    10.128.16.71   inf7    <none>           <none>
stress-cpu-server-inf44-rg27q   1/1     Running   0          86s    10.128.8.33    inf44   <none>           <none>
stress-cpu-server-inf7-wmthm    1/1     Running   0          4m3s   10.128.16.81   inf7    <none>           <none>
iperf3 % oc rsh iperf-2cd6j
sh-5.1$ iperf3 --client 10.128.16.71 --time 60 --parallel 4
...


```


<details>
  <summary>stress-inf7.yaml</summary>
  
```yaml
kind: Pod
apiVersion: v1
metadata:
  generateName: stress-cpu-server-inf7-
  labels:
    app: stress-cpu-server-inf7
spec:
  containers:
    - name: stress-cpu
      image: 'quay.io/dfroehli/tools-stress:latest'
      env:
        - name: STRESS_ARGS
          value: '--cpu 22'
      resources:
        requests:
          cpu: 22
          memory: 1024Mi
        limits:
          cpu: 22
          memory: 1024Mi
      imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: inf7
  tolerations:
  - key: "node.kubernetes.io/unschedulable"
    operator: "Exists"
    effect: "NoSchedule"

```
</details>

<details>
  <summary>stress-inf44.yaml</summary>
  
```yaml
kind: Pod
apiVersion: v1
metadata:
  generateName: stress-cpu-server-inf44-
  labels:
    app: stress-cpu-server-inf44
spec:
  containers:
    - name: stress-cpu
      image: 'quay.io/dfroehli/tools-stress:latest'
      env:
        - name: STRESS_ARGS
          value: '--cpu 10'
      resources:
        requests:
          cpu: 10
          memory: 1024Mi
        limits:
          cpu: 10
          memory: 1024Mi
      imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/hostname: inf44
  tolerations:
  - key: "node.kubernetes.io/unschedulable"
    operator: "Exists"
    effect: "NoSchedule"

```
</details>

<details>
  <summary>iperf DaemonSet</summary>
  
```yaml
kind: DaemonSet
apiVersion: apps/v1
metadata:
  annotations:
  name: iperf
  labels:
    app: iperf
spec:
  selector:
    matchLabels:
      app: iperf
  template:
    metadata:
      labels:
        app: iperf
    spec:
      nodeSelector:
        iperf-deploy: 'true'
      tolerations:
      - key: "node.kubernetes.io/unschedulable"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
        - name: server
          image: 'quay.io/dfroehli/tools-iperf:latest'
          resources:
            requests:
              cpu: 4
              memory: 128Mi
            limits:
              cpu: 4
              memory: 128Mi
          ports:
            - containerPort: 5201
              protocol: TCP
          env:
            - name: IPERF_OPT
              value: '--server'
      securityContext: {}
"

```
</details>


Again, I cannot reproduce. But a might, a massive change: We moved away ODF from inf7,inf8 and inf44!

https://github.com/stormshift/support/issues/204


@DanielFroehlich feel free to reopen, but then please schedule a meeting for us to test together!
