### ISSUE TITLE
observability-thanos-receive-default  (statefulset) - DOWN

### ISSUE THREAD

**Issue by rbo** [stormshift/support#203]
during #202 the observability-thanos-receive-default  (statefulset)  "lost" all pods. Because I deleted these.

Problem is new ones not scheduled because of:
```
create Pod observability-thanos-receive-default-0 in StatefulSet observability-thanos-receive-default failed error: Pod "observability-thanos-receive-default-0" is invalid: spec.containers[0].resources.requests: Invalid value: "300m": must be less than or equal to cpu limit of 0

```

Pod spec:
```yaml
...
      containers:
        - resources:
            limits:
              cpu: '0'
              memory: 2Gi
            requests:
              cpu: 300m
              memory: 512Mi

...
```
