### ISSUE TITLE
Investigate local quay performance

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#239]
The local quay instance on ISAR seems to be slow. Installing/pulling from it is not faster, sometimes even slower then from quay.io.
That should not be the case - its running local on 10G network with all flash ODF storage.

**Comment by DanielFroehlich** [comment]
raw network performance is fine - measuring  TLS via the router (using a tls-sni capable iperf version, see attachment for deployment of that) results in around 8Gi/s, which is expected considering the 10 Gi/s infra we have in the lab.

[deploy-iperf-tls-via-route.txt](https://github.com/user-attachments/files/18646166/deploy-iperf-tls-via-route.txt)

**Comment by DanielFroehlich** [comment]
storage seems to be an issue. Quay currently uses an object bucket via noobaa gateway.
Measuring that performance results in disappointing 15 MiB/s.
Same test using the rgw endpoint results in much better 150 MiB/s (but still below expected >1 GiB/s)
See [this gist ](https://gist.github.com/DanielFroehlich/a448b8911d3d8a78c41149493d22fba3
)for a scribble on how to do s3 performance benchmarking using `warp`tool

**Comment by DanielFroehlich** [comment]
Will switch storage backend from noobaa to rgw. SME discussion on how to do this on [internal slack](https://redhat-internal.slack.com/archives/C7WH69HCY/p1738762068616119).  
Will add summary of the procedure here or in a gist when done. 
Maintenance window for quay for Thu Feb 6 announced in slack and on quay.

**Comment by DanielFroehlich** [comment]
# Procedure to switch Quay Object storage from managed noobaa to unmanaged ceph rgw:

## Disable pushes
Quay config is gitops managed. To disable pushes:
1. Edit in git repo stormshift-clusters file  isar-apps/quay/30_config-bundle-ext-secret.yaml
Add: in config.yaml DISABLE_PUSHES: true
1. use ISAR Argo to sync
1. wait a while for quay to pick this up (watch the pods restarting) 
1.  try to push something if you want to be sure, it should fail
1. Using the quay admin console, you can add a nice error message to users so that they are aware of the maintenance
 
## Create new object storage
1. Use the ocp console to create a new bucket in rgw object storage class
, name it e.g. registry-quay-datastore-rgw
1. note the new access and secret key, bucket class. Also, note hostname of the route of the rgw for external access

## Copy / sync from the old bucket to the new one
Note: I tried with aws s3 command line tooling, but this seems not work with noobaa. Hence:

### Get rclone tooling
1. Grab a node / VM somewhere close to the cluster - as it will download/upload the whole bucket, it creates a lot of traffic. Avoid doing this on your local laptop via VPN. 
1. Download and install from https://rclone.org/downloads/

### Configure rclone
```
$ cat /home/builder/.config/rclone/rclone.conf
[coe-quay-nooba]
type = s3
provider = IBMCOS 
access_key_id = <<< from object bucket claim >>>
secret_access_key =  <<< from object bucket claim >>>
endpoint =  <<< from noobaa route, e.g. https://s3-openshift-storage.apps.isar.coe.muc.redhat.com/ >>>

[coe-quay-rgw]
type = s3
provider = Ceph 
access_key_id = <<< from object bucket claim >>>
secret_access_key = <<< from object bucket claim >>>
endpoint = <<< from rgw route, e.g. https://ocs-storagecluster-cephobjectstore-secure-openshift-storage.apps.isar.coe.muc.redhat.com/ >>>
```
**Note** the provider settings! Thats not straight forward and took me some experimentation

### Perform the sync:
```
$ rclone --no-check-certificate sync coe-quay-nooba:quay-datastore-1fb7edb0-143b-4892-a7e9-1d5530e46ad8 coe-quay-rgw:registry-quay-datastore-rg-fa0c480b-d7eb-4dc9-8d23-fefd58ee921d -P
```
Replace with the object bucket names accordingly.
You should see the syncing happening. Could try a 2nd time with not objects beeing transferred.

## Config Quay to use the new unmanaged object store
**Keep in mind**: ISAR cluster is gitops managed, you have to do the following steps in git and use Argo to sync changes

1. Find the config bundle secret (see first step). Add:
```
          DISTRIBUTED_STORAGE_CONFIG:
            local_us:
            - RHOCSStorage
            - access_key: {{ .storage_access_key }}
              bucket_name: registry-quay-datastore-rg-fa0c480b-d7eb-4dc9-8d23-fefd58ee921d
              hostname: ocs-storagecluster-cephobjectstore-secure-openshift-storage.apps.isar.coe.muc.redhat.com
              is_secure: true
              port: 443
              secret_key: {{ .storage_secret_key }}
              storage_path: /datastorage/registry
          DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS:
          - local_us
          DISTRIBUTED_STORAGE_PREFERENCE:
          - local_us
```
access/secret key from the rgw bucket. 
hostname is the external route (that is important! Not the internal service name!)
2. Find the QuayRegistry CR 
3. Set the objectstorage to unmaned:
```
    - kind: objectstorage
      managed: false
```
4. Watch the quay pods to restart to pickup the change
5. Try to pull an image, it should work

## Enable pushing again
See first step, just set it to `false`again. 

## Enjoy better performance
Some measurements of pulling a 1.5G image:
Before with noobaa:
```
real	2m2.231s
real	2m4.766s
````
 
After with rgw:
```
real	1m0.802s
real	0m55.188s
```

Pull time is half Yes!
