### ISSUE TITLE
ODF+LVMS update not possible

### ISSUE THREAD

**Issue by DanielFroehlich** [stormshift/support#265]
ODF update not starting:
```
constraints not satisfiable: no operators found in channel alpha of package cephcsi-operator in the catalog referenced by subscription 
cephcsi-operator-stable-4.17-redhat-operators-openshift-marketplace, subscription cephcsi-operator-stable-4.17-redhat-operators-openshift-marketplace exists
```
alpha channel does not any longer exist
cannot replace it in the managed operators, as the odf operator switch back to alpha channel
Could this be a bug in the odf operator?

This also blocks LVMS update, as they are in the same namespace.

**Comment by jeichler** [comment]
One of the issues might be: `no operators found from catalog odf-catalogsource in namespace openshift-marketplace referenced by subscription noobaa-operator, subscription noobaa-operator exists`

The catalogsource simply doesn't exist (anymore?).

**Comment by rbo** [comment]
```
$ oc get subscriptions.operators
NAME                                                                         PACKAGE                   SOURCE              CHANNEL
cephcsi-operator-stable-4.17-redhat-operators-openshift-marketplace          cephcsi-operator          redhat-operators    alpha
csi-addons                                                                   csi-addons                odf-catalogsource   alpha
lvms                                                                         lvms-operator             redhat-operators    stable-4.18
mcg-operator-stable-4.14-redhat-operators-openshift-marketplace              mcg-operator              redhat-operators    stable-4.17
noobaa-operator                                                              noobaa-operator           odf-catalogsource   alpha
ocs-client-operator                                                          ocs-client-operator       redhat-operators    alpha
ocs-operator-stable-4.14-redhat-operators-openshift-marketplace              ocs-operator              redhat-operators    alpha
odf-csi-addons-operator-stable-4.14-redhat-operators-openshift-marketplace   odf-csi-addons-operator   redhat-operators    stable-4.17
odf-operator                                                                 odf-operator              redhat-operators    stable-4.18
odf-prometheus-operator-stable-4.16-redhat-operators-openshift-marketplace   odf-prometheus-operator   redhat-operators    beta
recipe-stable-4.16-redhat-operators-openshift-marketplace                    recipe                    redhat-operators    alpha
rook-ceph-operator-stable-4.16-redhat-operators-openshift-marketplace        rook-ceph-operator        redhat-operators    alpha
$ oc get catalogsources -A
NAMESPACE               NAME                         DISPLAY                       TYPE   PUBLISHER   AGE
openshift-marketplace   acm-custom-registry          Advanced Cluster Management   grpc   Red Hat     359d
openshift-marketplace   certified-operators          Certified Operators           grpc   Red Hat     554d
openshift-marketplace   community-operators          Community Operators           grpc   Red Hat     520d
openshift-marketplace   multiclusterengine-catalog   MultiCluster Engine           grpc   Red Hat     359d
openshift-marketplace   redhat-marketplace           Red Hat Marketplace           grpc   Red Hat     554d
openshift-marketplace   redhat-operators             Red Hat Operators             grpc   Red Hat     554d

$ oc delete subscriptions.operators csi-addons
subscription.operators.coreos.com "csi-addons" deleted
$ oc delete subscriptions.operators noobaa-operator
subscription.operators.coreos.com "noobaa-operator" deleted
$ oc get subscriptions.operators
NAME                                                                         PACKAGE                   SOURCE              CHANNEL
cephcsi-operator-stable-4.17-redhat-operators-openshift-marketplace          cephcsi-operator          redhat-operators    alpha
csi-addons                                                                   csi-addons                odf-catalogsource   alpha
lvms                                                                         lvms-operator             redhat-operators    stable-4.18
mcg-operator-stable-4.14-redhat-operators-openshift-marketplace              mcg-operator              redhat-operators    stable-4.17
noobaa-operator                                                              noobaa-operator           odf-catalogsource   alpha
ocs-client-operator                                                          ocs-client-operator       redhat-operators    alpha
ocs-operator-stable-4.14-redhat-operators-openshift-marketplace              ocs-operator              redhat-operators    alpha
odf-csi-addons-operator-stable-4.14-redhat-operators-openshift-marketplace   odf-csi-addons-operator   redhat-operators    stable-4.17
odf-operator                                                                 odf-operator              redhat-operators    stable-4.18
odf-prometheus-operator-stable-4.16-redhat-operators-openshift-marketplace   odf-prometheus-operator   redhat-operators    beta
recipe-stable-4.16-redhat-operators-openshift-marketplace                    recipe                    redhat-operators    alpha
rook-ceph-operator-stable-4.16-redhat-operators-openshift-marketplace        rook-ceph-operator        redhat-operators    alpha
```

**Comment by rbo** [comment]
Let's try to create dummy catalogsources:

```
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: odf-catalogsource
  namespace: openshift-marketplace
spec:
  displayName: odf-catalogsource
  grpcPodConfig:
    extractContent:
      cacheDir: /tmp/cache
      catalogDir: /configs
    memoryTarget: 30Mi
    nodeSelector:
      kubernetes.io/os: linux
      node-role.kubernetes.io/master: ""
    priorityClassName: system-cluster-critical
    securityContextConfig: restricted
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
      operator: Exists
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 120
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 120
  icon:
    base64data: ""
    mediatype: ""
  image: registry.redhat.io/redhat/redhat-operator-index:v4.18
  priority: -100
  publisher: Red Hat
  sourceType: grpc
  updateStrategy:
    registryPoll:
      interval: 10m
```

=> doesn't work. Deleted...


Patched all catalogsources to redhat-operators via:

```shell
 1028  oc patch sub csi-addons --namespace openshift-storage --type merge --patch '{"spec":{"source":"redhat-operators"}}'
 1029  oc get subscriptions.operators
 1030  oc patch sub noobaa-operator --namespace openshift-storage --type merge --patch '{"spec":{"source":"redhat-operators"}}'
 1031  oc patch sub recipe --namespace openshift-storage --type merge --patch '{"spec":{"source":"redhat-operators"}}'
 1032  oc patch sub rook-ceph-operator --namespace openshift-storage --type merge --patch '{"spec":{"source":"redhat-operators"}}'
```
