### ISSUE TITLE
Switch off audit logging

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#34]
Consumes too many resources

**Comment by Javatar81** [comment]
Removed object 

```
apiVersion: logging.openshift.io/v1
kind: ClusterLogForwarder
metadata:
  name: instance
  namespace: openshift-logging
spec:
  inputs:
    - name: audit
  outputs:
    - name: remote
      type: fluentdForward
      url: 'tcp://fluentd.openshift-logging-to-nfs.svc.cluster.local:24224'
  pipelines:
    - inputRefs:
        - audit
      name: forward-to-remote
      outputRefs:
        - remote
        - default
```
