### ISSUE TITLE
Fix OpenShift Curator Job Errors

### ISSUE THREAD

**Issue by Javatar81** [stormshift/support#41]
Address this issue:

![Screenshot 2021-10-04 at 11 08 32](https://user-images.githubusercontent.com/19833550/135824492-cfd15c56-d9c0-4dad-bd83-919d001c8f71.png)

**Comment by Javatar81** [comment]
Removed the following part in the ClusterLogging to get rid of the curator job:

```
curation:
    curator:
      schedule: 30 3 * * *
    type: curator
```
