### ISSUE TITLE
Move rdp.coe.muc.redhat.com from inf48 to coe ocp-v

### ISSUE THREAD

**Issue by rbo** [stormshift/support#98]

**Comment by rbo** [comment]
```
[root@inf48 images]# qemu-img convert -O qcow2 /dev/nvme/win10 /var/lib/libvirt/images/windows10-root-disk.qcow2
```

**Comment by rbo** [comment]
#### Create PVC with qcow2:

![image](https://user-images.githubusercontent.com/36604/178736585-3d2064b3-00b4-47d8-9209-4562a1e6fa03.png)

![image](https://user-images.githubusercontent.com/36604/178737141-2e1deef2-2325-4e42-9ec7-10aa84f05c11.png)


#### Create service

```yaml
apiVersion: v1
kind: Service
metadata:
  labels:
    app: windows-10-rdp
  annotations:
    metallb.universe.tf/allow-shared-ip: "rdp-coe-muc-redhat-com"
  name: rdp-coe-muc-redhat-com-3389-udp
  namespace: rdp-service
spec:
  ports:
  - name: rdp
    port: 3389
    protocol: UDP
    targetPort: 3389
  selector:
    vm.kubevirt.io/name: windows-10-rdp
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: windows-10-rdp
  annotations:
    metallb.universe.tf/allow-shared-ip: "rdp-coe-muc-redhat-com"
  name: rdp-coe-muc-redhat-com-3389-tcp
  namespace: rdp-service
spec:
  ports:
  - name: rdp
    port: 3389
    protocol: TCP
    targetPort: 3389
  selector:
    vm.kubevirt.io/name: windows-10-rdp
  sessionAffinity: None
  type: LoadBalancer

```

#### Update DNS rdp.coe.muc.redhat.com
```
$ dig A +short rdp.coe.muc.redhat.com
10.32.98.152
```
